### ISSUE TITLE
[WiP]Poject recap

### ISSUE THREAD

**Issue by SebastianLF** [chingu-voyages/v11-bears-team-08#23]
Trainer Schema Modeling:
_Option 1:_
```
TRAINER
{
  _id: ObjectId
  firstName: String
  lastName: String
  email: String
  password: String
  gender: String
  location: String
  avatar: String    // image url
  presentation: String
  specialities: [String]      // 'Weight loss', 'Nutrition', 'HIIT'
  reviews: [ { stars: Number, sender: String, text: String } ]
  conversations: [],
  contacts: []
}
```

_Option 2:_
```
USER
{
  _id: ObjectId
  firstName: String
  lastName: String
  email: String
  password: String
  profiles: {
    trainer: trainer_id
  }
}
```
```
TRAINER
{
  _id: ObjectId
  gender: String
  location: String
  avatar: String
  presentation: String
  specialities: [String]
  reviews: []
  conversations: [],
  contacts: []
}
```
_Option 3:_
```
USER
{
  _id: ObjectId
  firstName: String
  lastName: String
  email: String
  password: String
}
```
```
TRAINER
{
  _id: ObjectId
  user_id: ObjectId     // Here!
  gender: String
  location: String
  avatar: String
  presentation: String
  specialities: [String]   
  reviews: []
  conversations: [],
  contacts: []
}
```

#### Rules:

1. (Mondo Schema Modeling) A conversation is only created when a user sends a message to a personal trainer that he's never contacted before.
e.g:  User named Alicia contacts Brad throught the website form. 
She says: "Hello! what are your rates?"

Results in:
```
Create a new conversation
{
  _id: 123
  members: [6, 5],        // Members ids.
  messages: [
    { 
      sender_id: 5,      /// Alicia id
      sender: 'Alicia', 
      text: 'Hello! what are your rates?', 
      created_at: '19/09/19'
   }
  ]
}
```
```
Update Alicia document
{
  _id: 5
  ...
  firstname: 'Alicia',
  ...
  conversations: [123]      // push id of convo with Brad.
  contacts: [6]     // push Brad's id.
}
```

```
Update Brad document
{
  _id: 6
  ...
  firstname: 'Brad',
  ...
  conversations: [123]      // push id of convo with Alicia.
  contacts: [5]     // push Alicia's id.
}
```

2. (Front end) Users and Trainers can access recent conversations from side panel. Clicking on the conversations opens up corresponding page (on the right side) that displays the conversation in detail.
A red dot indicates that a new message has been received

_Note:_ These features are available for Trainer and Client.

Results in:
![Capture du 2019-09-19 01-04-30](https://user-images.githubusercontent.com/7540595/65193176-7bd60680-da7a-11e9-8996-8be8d1952ff2.png)

![Capture du 2019-09-19 01-36-55](https://user-images.githubusercontent.com/7540595/65195152-50551b00-da7e-11e9-8026-03365d958aba.png)

#### Backend API routes: 

* POST `/api/conversations/`
    * requires to be authed
    * requires to pass `req.body.client._id` `req.body.trainer._id` `req.body.message`
    * returns whole conversation  

#### Frontend routes:
_//TODO_ 

#### Rules:

1. Both client and trainer are able to send each other appointments.

// TODO

## to be decided:
- What framework to use for front end routing? which version?
#### Db:
- what the best trainer schema?
    - For now, Option 2

#### Backend:
- Api routes for conversations 
    - For now, /api/conversations/
- Api routes for apointments

#### Frontend: 
- Login and Singup routes?
    - For now, /login & /singup

#### Design:
- What looks like 'search' page with trainers displayed.
- What looks like the trainer 'info' page (specialities, presentation...)
- What looks like the page which gives the coach the possibility to modify his information.

**Comment by fletcher-greg** [comment]
Agree with your points 

### Back-end
- JWT needs to be set up


### Front-end
- React Router for routing

**Comment by fletcher-greg** [comment]
I think I prefer option 2 for the mongoose schema.  Everyone is a user but some users are trainers.  If they're just users, its simple to pull in that data.  If a user is trainer then we pull in trainer data also. 

Also, users will need conversations and message arrays, so we can put that in the user schema.  This means we only have trainer specific data in the trainer schema

**Comment by fletcher-greg** [comment]
This is the schema for storing the messages. 
I've made a PR #26 adding this to our database structure 

```
const messageSchema = new Schema(
  {
    message: {
      text: { type: String, required: true }
    },

    users: [
      {
        user: {
          type: Schema.Types.ObjectId,
          ref: 'User',
          required: true
        }
      }
    ],
    sender: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true
    },
    read: { type: Date }
  },
  {
    timestamps: true
  }
)

```

**Comment by fletcher-greg** [comment]
I've made a PR #24 for the message container

**Comment by SebastianLF** [comment]
Useless now.
