### ISSUE TITLE
Login Feat

### ISSUE THREAD

**Issue by fletcher-greg** [chingu-voyages/v11-bears-team-08#7]
As a user, I want to see a login page, enter my details and login into my account

Considerations: Option to use Email or username?

Test:
Tapping on Login takes me to the Login form
Be able to enter my details
Finally, I press Login and go my Homepage
NOTE: Under the form I have a button to register (easy access for unregistered users)

**Comment by lunify** [comment]
Definitely email as the login option, since users would be known with their full name instead
